In [62]:
class Club:
    def __init__(self,svet) -> None:
        self.__svet1 = svet
    @property
    def svet(self):
        return self.__svet1
    @svet.setter
    def svet(self,om):
        if om=="Salom":self.svet1 = om
        else:pass
    def get_motod(self):
        return self.__svet1
Fut=Club("Hello")
print(Fut.svet)
print(Fut.get_motod())


Hello
Hello


In [63]:
class Uzbekistan:
    def __init__(self,poytaxt,aholi):
        self.poytaxt = poytaxt
        self.aholi = aholi
    def get_poytaxt(self):
        return self.poytaxt
class Kazakhistan:
    def __init__(self,poytaxt,aholi):
        self.poytaxt = poytaxt
        self.aholi = aholi
    def get_poytaxt(self):
        return self.poytaxt
city=Kazakhistan("Astana",24000000)
city=Uzbekistan("Toshkent",34000000)


In [64]:
print(city.get_poytaxt())
print(city.get_poytaxt())

Toshkent
Toshkent


In [65]:
import re
class Davlat:
    def __init__(self,poytaxt,aholi,viloyatlar_soni) -> None:
        self.poytaxt = poytaxt
        self.aholi = aholi
        self.viloyatlar_soni = viloyatlar_soni
    @property
    def poytaxt(self):
        return self.__poytaxt
    @poytaxt.setter
    def poytaxt(self,nomi):
        if re.match(r"[A-Z]",nomi):
            self.__poytaxt = nomi
        else:raise ValueError("Poytaxt nomi xato kiritilgan!")

    @property
    def aholi(self):
        return self.__aholi
    @aholi.setter
    def aholi(self,soni):
        if re.fullmatch(r"[0-9]+", soni):
            self.__aholi = soni
        else: 
            raise ValueError("Aholi soni xato kiritildi! ")

    @property
    def viloyat(self):
        return self.__viloyatlar_soni
    @viloyat.setter
    def viloyat(self,vsoni):
        if re.fullmatch(r"[0-9]+",vsoni):
            self.__viloyatlar_soni = vsoni
        else: 
            raise ValueError("Viloyatlar soni xato kiritildi! ")
        




In [66]:
davlat1=Davlat("Astana",'25000',15)

In [67]:
import numpy as np
b = np.array([1,2,3,4,5])
print(b)
print(type(b))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [68]:
import time
import random

In [75]:
a = [random.randint(1,9) for i in range(1000000)]
start = time.time()
print(sum(a)/len(a), time.time()-start)


5.002981 0.009474515914916992


In [ ]:
b = np.random.random(1000000)
start=time.time()
print(np.mean(b), time.time()-start)


0.49979008926968815 0.0025320053100585938


In [81]:
a = [int(i) for i in range(5,10)]
print(a)

[5, 6, 7, 8, 9]


In [15]:
import numpy as np
b = np.array([1,2,3,4,5])
print(b)

[1 2 3 4 5]


In [24]:
a = np.array([[1,2,3,4,5],[5,2,5,6,7]], ndmin=2)
print(a)
print(a.ndim)


[[1 2 3 4 5]
 [5 2 5 6 7]]
2


In [30]:
a = np.array([5,6,7,8,9])
a=a%2
print(a)

[1 0 1 0 1]


In [91]:
a=np.array([[1,2,3,4,5],[2,15,52,40,51],[11,52,43,654,55],[51,51,53,74,15],[21,32,63,44,58],[10,14,75,8,5]])
print(a[2:5,1:4])
a.ndim

[[ 52  43 654]
 [ 51  53  74]
 [ 32  63  44]]


2

In [92]:
import numpy as np

In [122]:
a = np.array(['45',1j+5,8.5,6.4525])
print(a.dtype)
print(a)

<U64
['45' '(5+1j)' '8.5' '6.4525']


In [150]:
a = np.array([4.05,0.158518,8.5,6.4525],dtype='f')
print(a)
a=a.astype(bool)
print(a)

[4.05     0.158518 8.5      6.4525  ]
[ True  True  True  True]


In [156]:
a=np.array([[1,2,3,4,5,1]])
print(a)
print(a.shape)
a = a.reshape(2,3)
print(a)

[[1 2 3 4 5 1]]
(1, 6)
[[1 2 3]
 [4 5 1]]


In [172]:
import numpy as np
a=np.arange(4,13)
a= a.reshape(3,3)
print(a)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [178]:

print(np.arange(5,14).reshape(3,3))
print(np.arange(5,14).reshape(3,3).base)

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
[ 5  6  7  8  9 10 11 12 13]


In [192]:
a = np.array([[1,5,4,8,7],[9,5,1,2,6],[7,5,4,8,2]]).reshape(5,3)
print(a.shape)
print(a)
print(a.base)

(5, 3)
[[1 5 4]
 [8 7 9]
 [5 1 2]
 [6 7 5]
 [4 8 2]]
[[1 5 4 8 7]
 [9 5 1 2 6]
 [7 5 4 8 2]]
