In [1]:
import numpy as np
a = np.array([[[1,2,3],
                 [10,2,8],
                 [8,7,6]],
                 [[5,6,4],
                  [14,53,19],
                  [6,1,9]],
                  [[2,5,3],
                   [8,5,7],
                   [9,5,1]]])
print(a)
print(a.shape)
a.ndim

[[[ 1  2  3]
  [10  2  8]
  [ 8  7  6]]

 [[ 5  6  4]
  [14 53 19]
  [ 6  1  9]]

 [[ 2  5  3]
  [ 8  5  7]
  [ 9  5  1]]]
(3, 3, 3)


3

In [2]:
import numpy as np

a = np.array([i for i in input().split()],dtype='U3')
print(a)


['5']


In [3]:
a = [i for i in range(1,50)]
print(a,end=' ')

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49] 

In [4]:
a = np.array([[1,2,3,4],[9,8,7,6]])
b= np.mat(a,dtype=np.int16)
a[1,2]=100
print(b)
print(a)

[[1 2 3 4]
 [9 8 7 6]]
[[  1   2   3   4]
 [  9   8 100   6]]


In [5]:
a = np.array([[1,2,3,4],[9,8,7,6]])
b= np.mat(a,dtype=np.int16)
a[1,2]=100
print(b)
print(a)

[[1 2 3 4]
 [9 8 7 6]]
[[  1   2   3   4]
 [  9   8 100   6]]


In [6]:
a = np.array(([1,2,3,4,5],[9,8,7,4,5],[9,5,1,2,4])).reshape(-1)
print(a)

[1 2 3 4 5 9 8 7 4 5 9 5 1 2 4]


In [10]:
a = np.logspace(5,15)
print(a)
b= np.linspace(1,15,5,endpoint=True)

[1.00000000e+05 1.59985872e+05 2.55954792e+05 4.09491506e+05
 6.55128557e+05 1.04811313e+06 1.67683294e+06 2.68269580e+06
 4.29193426e+06 6.86648845e+06 1.09854114e+07 1.75751062e+07
 2.81176870e+07 4.49843267e+07 7.19685673e+07 1.15139540e+08
 1.84206997e+08 2.94705170e+08 4.71486636e+08 7.54312006e+08
 1.20679264e+09 1.93069773e+09 3.08884360e+09 4.94171336e+09
 7.90604321e+09 1.26485522e+10 2.02358965e+10 3.23745754e+10
 5.17947468e+10 8.28642773e+10 1.32571137e+11 2.12095089e+11
 3.39322177e+11 5.42867544e+11 8.68511374e+11 1.38949549e+12
 2.22299648e+12 3.55648031e+12 5.68986603e+12 9.10298178e+12
 1.45634848e+13 2.32995181e+13 3.72759372e+13 5.96362332e+13
 9.54095476e+13 1.52641797e+14 2.44205309e+14 3.90693994e+14
 6.25055193e+14 1.00000000e+15]


In [11]:
a = np.array(([[1,2,3,4],[5,4,6,8]]))
b = np.array(([[0,6,7,8],[4,8,9,6]]))
c=np.array(([i for i in b]+[i for i in a]))
d = np.append(a,b)
t=np.concatenate([a,b])
print(t)
#print(c,'\n',d)
t.shape

[[1 2 3 4]
 [5 4 6 8]
 [0 6 7 8]
 [4 8 9 6]]


(4, 4)

In [12]:
a = np.array(([[1,2,3,4],[5,4,6,8]]))
b = np.array(([[0,6,7,8],[4,8,9,6]]))
c = np.vstack([a,b])
print(c)
c.shape

[[1 2 3 4]
 [5 4 6 8]
 [0 6 7 8]
 [4 8 9 6]]


(4, 4)

In [13]:
a = np.array(([[1,2,3,4],[5,4,6,8]]))
b = np.array(([[0,6,7,8],[4,8,9,6]]))
c = np.dstack([a,b])
print(c)
c.shape

[[[1 0]
  [2 6]
  [3 7]
  [4 8]]

 [[5 4]
  [4 8]
  [6 9]
  [8 6]]]


(2, 4, 2)

In [14]:
mas= [i for i in range(1,100)]
n=int(input())
k=0
l=0
while k<n:
    print(mas[n:l])
    k+=1
    l+=n
    print("k=",k,"l=",l,"n=",n)

[]
k= 1 l= 5 n= 5
[]
k= 2 l= 10 n= 5
[6, 7, 8, 9, 10]
k= 3 l= 15 n= 5
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
k= 4 l= 20 n= 5
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
k= 5 l= 25 n= 5


In [15]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.split(a,2)
print(b)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [16]:
a = np.array([[1,2],[3,4],[5,6],[7,8]])
b = np.array_split(a,5)
print(len(b))
print(b)

5
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]]), array([], shape=(0, 2), dtype=int32)]


In [17]:
a = np.zeros((4,4),dtype=int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [18]:
a = np.ones((4,4),dtype=int)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [19]:
a = np.zeros_like(([4,4]),dtype=int)
print(a)

[0 0]


In [20]:
a = np.tri(3,6,dtype=np.int8)
print(a)

[[1 0 0 0 0 0]
 [1 1 0 0 0 0]
 [1 1 1 0 0 0]]


In [21]:
a = np.array([[1,2],
              [5,6]])
b = np.array(([9,8],
              [4,2]))
print(a&b)

[[1 0]
 [4 2]]


In [22]:
a = np.array([[1,2],
              [5,6]])
b = np.array(([9,8],
              [4,2]))
print(a@b)
print(np.matmul(a,b))

[[17 12]
 [69 52]]
[[17 12]
 [69 52]]


In [36]:
a = np.array([[-1,2,-3,0,5],[-10,52,32,14,51]])
a=a[(a<0) ^ (a>5)]
print(a)

[ -1  -3 -10  52  32  14  51]


In [38]:
a = np.array([[1,2,3,4,5],[10,52,32,14,51]])
print(*np.where(a%2==0))

[0 0 1 1 1 1] [1 3 0 1 2 3]


In [39]:
a = np.array([[1,4,5],
              [12,4,5],
              [5,15,8]]) 
print(np.linalg.det(a))
print(np.linalg.inv(a))

472.99999999999983
[[-9.09090909e-02  9.09090909e-02 -9.25185854e-18]
 [-1.50105708e-01 -3.59408034e-02  1.16279070e-01]
 [ 3.38266385e-01  1.05708245e-02 -9.30232558e-02]]


In [40]:
import numpy as np
print(np.__version__)

1.25.2
