Numpy functions

In [ ]:
import numpy as np
np.array()
np.arange()
np.linspace()
np.logspace()
np.geomspace()
np.zeros()
np.zeros_like()
np.ones()
np.ones_like()
np.empty()
np.empty_like()
np.full()
np.full_like()
np.eye()
np.identity()
np.diag()
np.diagflat()
np.tri()
np.tril()
np.triu()

np.finfo(type)
np.iinfo(type)

In [72]:
import numpy as np

In [6]:
a = np.logspace(1,3,3)
print(a)

[  10.  100. 1000.]


In [16]:
a = np.geomspace(1,50,4)
print(a)
for i in a:
  print("%.2f" % i,end=' ')

[ 1.          3.6840315  13.57208808 50.        ]
1.00 3.68 13.57 50.00 

In [70]:
b = np.zeros((3,3,5),dtype=np.int8)
print(b)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [77]:
b = np.zeros_like([[1,2,3,4],[7,8,9,5]],dtype=np.float16)
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [86]:
a = np.empty((3,3),dtype='int32')
print(a)


[[         0          0 1386262960]
 [     32764          1          0]
 [        -1         -1    7536640]]


In [90]:
np.full((5,4),[5,1,7,2])

array([[5, 1, 7, 2],
       [5, 1, 7, 2],
       [5, 1, 7, 2],
       [5, 1, 7, 2],
       [5, 1, 7, 2]])

In [92]:
a = np.array([1,2,3,4,5,6,7,8],dtype=np.float16)
np.full_like(a,0.5)

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5], dtype=float16)

In [3]:
import numpy as np
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
a = np.identity(3)
print(a)
a.shape

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


(3, 3)

In [111]:
a = np.random.random(16).reshape(4,4)
print(a)
print(np.diag(a))

[[0.9229989  0.79186733 0.36672602 0.70456336]
 [0.62887033 0.22928274 0.41661806 0.4378488 ]
 [0.55134873 0.93697901 0.92539698 0.96604701]
 [0.92210503 0.86162537 0.46522829 0.82178028]]
[0.9229989  0.22928274 0.92539698 0.82178028]


In [113]:
a = np.diagflat([1,2,3])
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [129]:
b=(np.tri(3))
a = np.array([[1,0,0],
     [1,1,0],
     [1,1,1]],dtype='float')
a = np.tril(a)
print(b,'\n','\n',a)

[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]] 
 
 [[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


In [132]:
np.tri(3,4,-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.]])

In [124]:
a = np.random.random(9).reshape(3,3)
a = np.tril(a)
print(a)

[[0.31822818 0.         0.        ]
 [0.27243278 0.87199451 0.        ]
 [0.97683452 0.4403414  0.18404666]]


In [122]:
a = np.random.random(12).reshape(3,4)
a = np.triu(a)
print(a)

[[0.6762313  0.70139114 0.47357974 0.24796035]
 [0.         0.30387137 0.37268797 0.23546458]
 [0.         0.         0.78730145 0.94855425]]


In [135]:
a = np.random.random(12).reshape(3,4)
print(a.itemsize)
print(a.nbytes)

8
96


Indexsing

In [141]:
a = np.array([1,2,3,4,5,6,7,8]).reshape(2,4)
print(a)
print(a[1:,2:])
print(a[(0,1,1,0,0,1,1,1,0),
        (1,3,2,1,3,2,0,1,2)])
print(a[a>4])
b = np.array([True,True,False,False,True,False,False,True]).reshape(2,4)
print(a[b])


[[1 2 3 4]
 [5 6 7 8]]
[[7 8]]
[2 8 7 2 4 7 5 6 3]
[5 6 7 8]
[1 2 5 8]


Operato'rs
+ - * / // @ & ^  |

In [144]:
a = np.array([2,3,5])
b = np.array([1,4,2])
print(a//b) 
print(a%b)
print(a@b)

[2 0 2]
[0 3 1]
24


In [5]:
a = np.array([2,3,5,4,4,9,6,1,22])
b = np.array([1,4,2,3,6,4,8,9,8])
print(a&b)
print(a^b)

[0 0 0 0 4 0 0 1 0]
[ 3  7  7  7  2 13 14  8 30]


python functions for array

In [166]:
a = np.array(np.random.random(27).reshape(3,3,3),dtype=np.float16)
print(a)
print(a.max())
print(a.min())
print(a.max(axis=2))

[[[0.78    0.6226  0.3953 ]
  [0.9873  0.528   0.4668 ]
  [0.1587  0.8877  0.2162 ]]

 [[0.4675  0.1501  0.0319 ]
  [0.1857  0.2957  0.0327 ]
  [0.3171  0.04254 0.6147 ]]

 [[0.52    0.9385  0.9087 ]
  [0.7686  0.2903  0.2141 ]
  [0.2678  0.743   0.0918 ]]]
0.9873
0.0319
[[0.78   0.9873 0.8877]
 [0.4675 0.2957 0.6147]
 [0.9385 0.7686 0.743 ]]


In [2]:
import numpy as np
a= np.arange(27).reshape(3,3,3)
print(a)
np.sum(a,axis=0)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[27, 30, 33],
       [36, 39, 42],
       [45, 48, 51]])

In [189]:
a = np.array((1,2,5,4))
b = np.array((2,5,4,6))
print((a>=b).any())
print(a>=b)
a= a[a>b]
print(a)
#any find 'True'
#all find 'False'

True
[False False  True False]
[5]


sort and search

In [10]:
a = np.random.random(27).reshape(3,3,3)
print(a)
print('\n')
print(np.sort(a,axis=1))

[[[0.28547458 0.38552896 0.03699252]
  [0.15191857 0.9197822  0.71379974]
  [0.23630217 0.86172592 0.29198627]]

 [[0.86494    0.05505545 0.01219245]
  [0.17122869 0.78927789 0.75259968]
  [0.66295021 0.62782823 0.78632243]]

 [[0.31778137 0.38112781 0.49677419]
  [0.92451039 0.93496472 0.43422358]
  [0.09708526 0.2444776  0.19513732]]]


[[[0.15191857 0.38552896 0.03699252]
  [0.23630217 0.86172592 0.29198627]
  [0.28547458 0.9197822  0.71379974]]

 [[0.17122869 0.05505545 0.01219245]
  [0.66295021 0.62782823 0.75259968]
  [0.86494    0.78927789 0.78632243]]

 [[0.09708526 0.2444776  0.19513732]
  [0.31778137 0.38112781 0.43422358]
  [0.92451039 0.93496472 0.49677419]]]


In [210]:
class Talaba:
    def __init__(self,ismi,yoshi,kursi) -> None:
        self.ismi = ismi
        self.yoshi = yoshi
        self.kursi = kursi       
talabalar = [Talaba('Ismoil',19,1),Talaba('Bobur',20,2),Talaba('Xolavat',18,0)]
for i in sorted(talabalar,key=lambda x:x.kursi):
    print(i.kursi,i.yoshi,i.ismi)



0 18 Xolavat
1 19 Ismoil
2 20 Bobur


In [11]:
import numpy as np

In [8]:
dtypes = [("Ismi",'U10'),('Yoshi','int8'),('Kursi','int8')]
a = np.array([('Ismoil',19,1),('Bobur',20,2),('Xolavat',18,3)],dtype=dtypes)
print(np.sort(a,order='Yoshi'))

[('Xolavat', 18, 3) ('Ismoil', 19, 1) ('Bobur', 20, 2)]


In [19]:
a = np.arange(0,2*np.pi,np.pi/2)
print(a)
print(np.sqrt(a))
print(np.exp(a))


[0.         1.57079633 3.14159265 4.71238898]
[0.         1.25331414 1.77245385 2.17080376]
[  1.           4.81047738  23.14069263 111.31777849]
